# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  test:
    machine:
      enabled: true
    steps:
      - run: echo "Test can run here!"
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Install Java & Maven
          command: ssh $SSH_USER@$SSH_HOST "sudo apt-get update && sudo apt-get install -y curl git && sudo apt-get install -y openjdk-8-jdk"
      - run:
          name: Pull most recent repo
          command: ssh $SSH_USER@$SSH_HOST "cd ~/SFIA-project && git pull"
      - run:
          name: Maven install
          command: ssh $SSH_USER@$SSH_HOST "cd ~/SFIA-project && sudo apt-get install -y maven"
      - run:
          name: Deploy Application
          command: ssh $SSH_USER@$SSH_HOST "cd ~/SFIA-project && mvn verify"
      - run:
          name: Delete Old DataBase
          command: ssh $SSH_USER@$SSH_HOST "rm -f sfia.mv.db"
      - run:
          name: Run application
          command: ssh $SSH_USER@$SSH_HOST "cd ~/SFIA-project && mvn -Dmaven.test.skip=true spring-boot:run"
          no_output_timeout: 45m
workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
